"""Add path indices

Revision ID: 3ca73109949d
Revises: 8e4e31afc0a2
Create Date: 2018-03-29 21:15:11.022500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ca73109949d'
down_revision = '8e4e31afc0a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_path_id'), 'path', ['id'], unique=False)
    op.create_index('parent_basename_idx', 'path', [
                    'parent_id', 'basename'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('parent_basename_idx', table_name='path')
    op.drop_index(op.f('ix_path_id'), table_name='path')
    # ### end Alembic commands ###
