"""Make index unique

Revision ID: 7ae41e19e0be
Revises: 3ca73109949d
Create Date: 2018-03-29 21:56:02.437234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ae41e19e0be'
down_revision = '3ca73109949d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('parent_basename_idx', table_name='path')
    op.create_index('parent_basename_idx', 'path', ['parent_id', 'basename'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('parent_basename_idx', table_name='path')
    op.create_index('parent_basename_idx', 'path', ['parent_id', 'basename'], unique=False)
    # ### end Alembic commands ###
