run_pytest: &run_pytest
    steps:
        - checkout
        - run: virtualenv venv
        - run:
            name: install
            command: |
                source venv/bin/activate
                pip install -e .[test]
        - run:
            name: test
            command: |
                source venv/bin/activate
                mkdir test-report
                py.test --junitxml=test-report/junit.xml
        - store_test_results:
            path: test-report
        - store_artifacts:
            path: test-report

version: 2

jobs:
    python2:
        docker:
            - image: circleci/python:2
        <<: *run_pytest
    python3:
        docker:
            - image: circleci/python:3
        <<: *run_pytest

workflows:
    version: 2
    pytest:
        jobs:
            - python2
            - python3
