run_pytest: &run_pytest
    steps:
        - checkout
        - run: virtualenv venv
        - run:
            name: install
            command: |
                source venv/bin/activate
                pip install -e .[test]
        - run:
            name: test
            command: |
                source venv/bin/activate
                mkdir -p test-report/pytest
                py.test --junitxml=test-report/pytest/junit.xml
        - store_test_results:
            path: test-report
        - store_artifacts:
            path: test-report

run_conda: &run_conda
    docker:
        - image: circleci/python
    steps:
        - checkout
        - run:
            name: install-conda
            command: |
                wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O conda.sh
                bash conda.sh -b -p ~/miniconda
        - restore_cache:
            keys:
                - conda-pkgs-{{ checksum "conda/meta.yaml" }}
                - conda-pkgs
        - run:
            name: setup
            command: |
                ~/miniconda/bin/conda install --yes conda-build anaconda-client
                ~/miniconda/bin/conda config --system --add channels conda-forge
        - run:
            name: build
            command: |
                ~/miniconda/bin/conda build conda/
        - save_cache:
            key: conda-pkgs-{{ checksum "conda/meta.yaml" }}
            paths:
                ~/miniconda/pkgs


version: 2

jobs:
    python2:
        docker:
            - image: circleci/python:2
        <<: *run_pytest
    python3:
        docker:
            - image: circleci/python:3
        <<: *run_pytest
    conda3:
        <<: *run_conda

workflows:
    version: 2
    pytest:
        jobs:
            - python2
            - python3
            - conda3
